import {useEffect,useState,useRef} from 'react';
import {Link} from 'react-router-dom';
import {useAccount} from '../AccountContext';
import {useSite} from '../SiteContext';
import {post,request,uploadImage} from '../api/client';

const tabs=['Overview','Categories','Website','Accounts','Shops','Listings','Subscriptions','Reports','Assessments','Audit'];
const blankCategory={name:'',slug:'',subtitle:'',image_path:'',position:0,enabled:true};
const currency=amount=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(amount/100);
const date=value=>value?new Date(value).toLocaleString():'—';

function QuoteReview({item,busy,onSuggest,onApprove}){
  const [amount,setAmount]=useState((item.approved_amount_minor||item.suggestion?.monthlyAmountMinor||49900)/100),[reason,setReason]=useState(item.reason||item.suggestion?.reason||'');
  return <form className="ait-panel ait-form" onSubmit={event=>{event.preventDefault();if(window.confirm(`Approve ₹${amount}/month for this shop? The customer must accept it before AutoPay.`))onApprove({amountMinor:Math.round(Number(amount)*100),reason,revision:item.revision});}}><h3>{item.name}</h3><p>{item.category} · {item.size} · {item.branches} branches · {item.expected_photos} photos</p><p>Status: {item.status}</p>{item.suggestion&&<p>AI suggestion (not approved): {currency(item.suggestion.monthlyAmountMinor)}/month — {item.suggestion.reason}</p>}<label>Monthly INR amount<input type="number" required min={499} max={100000} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Price explanation<textarea required minLength={10} maxLength={1500} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="ait-actions"><button type="button" disabled={busy} className="btn-secondary" onClick={onSuggest}>Get AI recommendation</button><button disabled={busy} className="btn-primary">Approve monthly quote</button></div></form>;
}

export default function ProductOwnerPage(){
  const {user,loading,setUser}=useAccount(),siteContext=useSite();
  const [tab,setTab]=useState('Overview'),[data,setData]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[offset,setOffset]=useState(0),[editCategory,setEditCategory]=useState(null),[code,setCode]=useState('');
  const activeTab=useRef('');activeTab.current=tab+':'+offset;
  async function load(){const requested=tab+':'+offset;setData(null);setError('');const result=await request(`/admin/${tab.toLowerCase()}?offset=${offset}`);if(activeTab.current===requested)setData(result);}
  useEffect(()=>{if(user?.role==='admin')load().catch(error=>setError(error.message));},[user?.role,tab,offset]);
  async function mutate(path,value,method='POST'){
    setBusy(true);setError('');setMessage('');
    try{const result=await request('/admin'+path,{method,body:JSON.stringify(value)});setMessage('Changes saved.');await load();await siteContext.refresh();return result;}catch(error){setError(error.message);return null;}finally{setBusy(false);}
  }
  async function claim(event){event.preventDefault();setBusy(true);try{const result=await post('/admin/claim-owner',{code});setUser(result.user);setCode('');}catch(error){setError(error.message);}finally{setBusy(false);}}
  if(loading)return <section className="ait-page">Loading…</section>;
  if(user?.role!=='admin')return <section className="ait-page ait-auth"><div className="ait-panel"><p className="ait-eyebrow">ALL IN ONE TODAY</p><h1>Product-owner login</h1><p>This control center is restricted to the software owner. Shop owners use their business dashboard.</p>{!user?<Link className="btn-primary" to="/login?next=/admin">Login</Link>:<form className="ait-form" onSubmit={claim}><p>First-time owner setup requires the private setup code and the designated owner account.</p><label>Owner setup code<input type="password" value={code} onChange={event=>setCode(event.target.value)} required minLength={40}/></label><button className="btn-primary" disabled={busy}>Activate owner controls</button></form>}{error&&<p className="ait-error" role="alert">{error}</p>}</div></section>;
  return <section className="ait-page ait-owner"><header className="ait-owner-header"><div><p className="ait-eyebrow">PRODUCT OWNER · ALL IN ONE TODAY</p><h1>Your marketplace control center.</h1><p>Manage content, people, shops and subscriptions in one place.</p></div><Link className="btn-secondary" to="/">View website ↗</Link></header>
    <div className="ait-owner-layout"><nav className="ait-owner-nav" aria-label="Owner controls">{tabs.map(item=><button key={item} type="button" className={tab===item?'selected':''} onClick={()=>{setData(null);setTab(item);setOffset(0);setMessage('');setEditCategory(null);}}>{item}</button>)}</nav><div className="ait-owner-main">
    {error&&<p role="alert" className="ait-error">{error}</p>}{message&&<p role="status" className="ait-notice">{message}</p>}
    {!data?<p>Loading {tab.toLowerCase()}…</p>:<>
    {tab==='Overview'&&<><h2>Overview</h2><div className="ait-stat-grid">{[['Accounts',data.accounts],['Shops',data.shops],['Active listings',data.listings],['Paid subscriptions',data.paid_subscriptions],['Pending reports',data.reports]].map(([label,value])=><article className="ait-panel" key={label}><p>{label}</p><strong>{value}</strong></article>)}</div><div className="ait-panel"><h3>Launch status</h3><p>Razorpay: {data.billingEnabled?'Configured':'Payment credentials / approved pricing pending'}</p><p>Google login: {data.googleEnabled?'Configured':'OAuth credentials pending'}</p><p>Only confirmed payments publish a shop. Website changes and moderation actions are recorded in the audit log.</p></div></>}
    {tab==='Categories'&&<><div className="ait-actions"><h2>Marketplace categories</h2><button className="btn-primary" onClick={()=>setEditCategory({...blankCategory,position:data.length})}>Add category</button></div>{editCategory?<CategoryEditor value={editCategory} busy={busy} onCancel={()=>setEditCategory(null)} onSave={async value=>{if(await mutate('/categories'+(editCategory.id?'/'+editCategory.id:''),value,editCategory.id?'PATCH':'POST'))setEditCategory(null);}}/>:data.map(item=><article className="ait-admin-row" key={item.id}>{item.image_path&&<img src={item.image_path} alt=""/>}<div><h3>{item.name}</h3><p>{item.subtitle} · {item.enabled?'Visible':'Hidden'}</p></div><button className="btn-secondary" onClick={()=>setEditCategory(item)}>Edit</button></article>)}</>}
    {tab==='Website'&&<WebsiteEditor key={data.revision} data={data} categories={siteContext.categories} busy={busy} onSave={value=>mutate('/website',value,'PUT')}/>}
    {tab==='Accounts'&&<><h2>Accounts</h2>{data.map(account=><article className="ait-admin-row" key={account.id}><div><h3>{account.name}</h3><p>{account.email}</p><small>{account.role} · {account.suspended?'Suspended':'Active'} · {date(account.created_at)}</small></div>{account.role!=='admin'&&<button className="btn-secondary" disabled={busy} onClick={()=>{if(window.confirm(`${account.suspended?'Restore':'Suspend'} this account?`))mutate('/accounts/'+account.id,{suspended:!account.suspended},'PATCH');}}>{account.suspended?'Restore':'Suspend'}</button>}</article>)}</>}
    {tab==='Shops'&&<><h2>Shop administration</h2>{data.map(shop=><article className="ait-admin-row" key={shop.id}><div><h3>{shop.name}</h3><p>{shop.category} · {shop.branches} branches · {shop.location}</p><small>{shop.owner_email} · {shop.status}</small></div><button disabled={busy} className="btn-secondary" onClick={()=>mutate('/shops/'+shop.id,{status:shop.status==='active'?'inactive':'active'},'PATCH')}>{shop.status==='active'?'Hide shop':'Publish paid shop'}</button></article>)}</>}
    {tab==='Listings'&&<><h2>Listing moderation</h2>{data.map(item=><article className="ait-admin-row" key={item.id}><div><h3>{item.title}</h3><p>{item.seller_name} · {item.category} · {item.status}</p><small>{item.description}</small></div><div className="ait-actions"><button disabled={busy} className="btn-secondary" onClick={()=>{const title=window.prompt('Listing title',item.title);if(title)mutate('/listings/'+item.id,{title,status:item.status==='active'?'active':'removed'},'PATCH');}}>Edit title</button><button disabled={busy} className="btn-secondary" onClick={()=>{if(window.confirm('Change the visibility of this listing?'))mutate('/listings/'+item.id,{status:item.status==='active'?'removed':'active'},'PATCH');}}>{item.status==='active'?'Remove':'Restore'}</button></div></article>)}</>}
    {tab==='Subscriptions'&&<><h2>Subscription records</h2><p>Payment access comes from verified Razorpay payments, not manual activation.</p>{data.map(item=><article className="ait-admin-row" key={item.id}><div><h3>{item.shop_name}</h3><p>{currency(item.amount_minor)} / {item.period} · {item.status}</p><small>{item.email} · Paid through {date(item.paid_until)}</small><p>{item.provider_id||'Provider creation pending'}</p></div></article>)}</>}
    {tab==='Reports'&&<><h2>Safety reports</h2>{data.map(report=><article className="ait-panel" key={report.id}><h3>{report.title}</h3><p>{report.reason}</p><div className="ait-actions"><button disabled={busy} className="btn-primary" onClick={()=>{if(window.confirm('Remove the reported listing?'))mutate('/reports/'+report.id,{remove:true});}}>Remove listing</button><button disabled={busy} className="btn-secondary" onClick={()=>mutate('/reports/'+report.id,{remove:false})}>Mark reviewed</button></div></article>)}</>}
    {tab==='Assessments'&&<><h2>Monthly shop quotes</h2><p>Small single-branch shops with up to 100 photos start at ₹499/month. Review larger shops, extra branches and storage-heavy categories here. AI suggestions never activate billing.</p>{data.map(item=><QuoteReview key={item.shop_id+':'+item.revision} item={item} busy={busy} onSuggest={()=>mutate('/assessments/'+item.shop_id+'/suggest',{})} onApprove={value=>mutate('/assessments/'+item.shop_id,value,'PUT')}/>)}</>}
    {tab==='Audit'&&<><h2>Owner activity</h2>{data.map((item,index)=><article className="ait-admin-row" key={index}><div><h3>{item.action}</h3><small>{item.actor} · {date(item.created_at)}</small><p>{item.target}</p></div></article>)}</>}
    {Array.isArray(data)&&!data.length&&<p className="ait-empty">No records here yet.</p>}
    {['Accounts','Shops','Listings','Subscriptions','Audit'].includes(tab)&&<div className="ait-actions"><button className="btn-secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>Previous</button><span>Records {offset+1}–{offset+data.length}</span><button className="btn-secondary" disabled={data.length<100} onClick={()=>setOffset(offset+100)}>Next</button></div>}
    </>}
    </div></div>
  </section>;
}

function CategoryEditor({value,busy,onSave,onCancel}){
  const [form,setForm]=useState(value),[error,setError]=useState('');
  const field=key=>({value:form[key],onChange:event=>setForm({...form,[key]:key==='position'?Number(event.target.value):event.target.value})});
  return <form className="ait-panel ait-form" onSubmit={event=>{event.preventDefault();onSave(form);}}><h2>{value.id?'Edit category':'New category'}</h2><label>Name<input required minLength={2} maxLength={50} {...field('name')}/></label><label>URL slug<input required pattern="[a-z0-9-]{2,60}" {...field('slug')}/></label><label>Subtitle<input maxLength={200} {...field('subtitle')}/></label><label>Image address<input {...field('image_path')}/></label><label>Upload category image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async event=>{try{if(event.target.files[0])setForm({...form,image_path:await uploadImage(event.target.files[0])});}catch(error){setError(error.message);}}}/></label><label>Display order<input type="number" min={0} max={1000} {...field('position')}/></label><label className="ait-checkbox"><input type="checkbox" checked={form.enabled} onChange={event=>setForm({...form,enabled:event.target.checked})}/>Visible to visitors</label>{error&&<p className="ait-error">{error}</p>}<div className="ait-actions"><button className="btn-primary" disabled={busy}>Save category</button><button type="button" className="btn-secondary" onClick={onCancel}>Cancel</button></div></form>;
}

function WebsiteEditor({data,categories,busy,onSave}){
  const [form,setForm]=useState(data.value),[active,setActive]=useState(0),[imageError,setImageError]=useState('');
  const section=form.sections[active];
  function updateSection(key,value){setForm({...form,sections:form.sections.map((item,index)=>index===active?{...item,[key]:value}:item)});}
  function move(direction){const target=active+direction;if(target<0||target>=form.sections.length)return;const items=[...form.sections];[items[active],items[target]]=[items[target],items[active]];setForm({...form,sections:items});setActive(target);}
  return <form className="ait-form" onSubmit={event=>{event.preventDefault();if(window.confirm('Publish these website changes?'))onSave({value:form,revision:data.revision});}}><h2>Website builder</h2><p>Edit component content, images, visibility and order. Changes are published to the website and category data used by the apps.</p>
    <div className="ait-panel ait-form"><h3>Brand and support</h3><label>Footer description<textarea value={form.tagline} onChange={event=>setForm({...form,tagline:event.target.value})}/></label><div className="ait-form-grid"><label>Support email<input type="email" value={form.supportEmail} onChange={event=>setForm({...form,supportEmail:event.target.value})}/></label><label>Support phone<input value={form.supportPhone} onChange={event=>setForm({...form,supportPhone:event.target.value})}/></label></div><div className="ait-actions">{Object.entries(form.theme).map(([key,value])=><label key={key}>{key}<input type="color" value={value} onChange={event=>setForm({...form,theme:{...form.theme,[key]:event.target.value}})}/></label>)}</div></div>
    <div className="ait-panel ait-form"><h3>Popular items</h3>{form.popular.map((item,index)=><div className="ait-form-grid" key={index}><input aria-label={`Popular label ${index+1}`} value={item.label} onChange={event=>setForm({...form,popular:form.popular.map((value,i)=>i===index?{...value,label:event.target.value}:value)})}/><div className="ait-actions"><select aria-label={`Popular category ${index+1}`} value={item.category} onChange={event=>setForm({...form,popular:form.popular.map((value,i)=>i===index?{...value,category:event.target.value}:value)})}>{categories.map(name=><option key={name}>{name}</option>)}</select><button type="button" className="ait-link" onClick={()=>setForm({...form,popular:form.popular.filter((_,i)=>i!==index)})}>Remove</button></div></div>)}<button type="button" className="btn-secondary" onClick={()=>setForm({...form,popular:[...form.popular,{label:'New item',category:categories[0]||''}]})}>Add popular item</button></div>
    <div className="ait-panel ait-form"><h3>Page components</h3><div className="ait-section-picker">{form.sections.map((item,index)=><button type="button" key={item.id} className={active===index?'selected':''} onClick={()=>setActive(index)}>{index+1}. {item.type} · {item.enabled?'On':'Off'}</button>)}</div>
      <button type="button" className="btn-secondary" onClick={()=>{setForm({...form,sections:[...form.sections,{id:'section-'+Date.now(),type:'text',enabled:true,title:'New component',body:''}]});setActive(form.sections.length);}}>Add component</button>
      {section&&<>
        <label>Component type<select value={section.type} onChange={event=>updateSection('type',event.target.value)}>{['hero','categories','listings','steps','text','banner','downloads','shops'].map(type=><option key={type}>{type}</option>)}</select></label>
        <label>Title<textarea aria-label="Title" required value={section.title} onChange={event=>updateSection('title',event.target.value)}/></label>
        <label>Description<textarea aria-label="Description" value={section.body} onChange={event=>updateSection('body',event.target.value)}/></label>
        <label>Image address<input value={section.image||''} onChange={event=>updateSection('image',event.target.value)}/></label>
        <label>Upload component image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async event=>{try{if(event.target.files[0])updateSection('image',await uploadImage(event.target.files[0]));}catch(error){setImageError(error.message);}}}/></label>
        {section.type==='listings'&&<label>Category filter<select value={section.category||''} onChange={event=>updateSection('category',event.target.value)}><option value="">All categories</option>{categories.map(name=><option key={name}>{name}</option>)}</select></label>}
        {section.type==='steps'&&<label>Steps (one title | description per line)<textarea value={(section.items||[]).map(item=>item.title+' | '+item.body).join('\n')} onChange={event=>updateSection('items',event.target.value.split('\n').filter(Boolean).map(line=>{const [title,...body]=line.split('|');return{title:title.trim(),body:body.join('|').trim()};}))}/></label>}
        <div className="ait-form-grid"><label>Button label<input value={section.button||''} onChange={event=>updateSection('button',event.target.value)}/></label><label>Button destination<input value={section.link||''} onChange={event=>updateSection('link',event.target.value)}/></label></div>
        <label className="ait-checkbox"><input type="checkbox" checked={section.enabled} onChange={event=>updateSection('enabled',event.target.checked)}/>Show component</label>
        <div className="ait-actions"><button type="button" className="btn-secondary" onClick={()=>move(-1)} disabled={active===0}>Move up</button><button type="button" className="btn-secondary" onClick={()=>move(1)} disabled={active===form.sections.length-1}>Move down</button><button type="button" className="ait-link" onClick={()=>{setForm({...form,sections:form.sections.filter((_,i)=>i!==active)});setActive(0);}}>Remove component</button></div>
      </>}
    </div>{imageError&&<p className="ait-error">{imageError}</p>}<button className="btn-primary" disabled={busy}>Publish website changes</button>
  </form>;
}

function PricingEditor({data,categories,busy,onSave}){
  const [period,setPeriod]=useState(data.period||'month'),[approved,setApproved]=useState(data.approved),[rates,setRates]=useState(categories.map(category=>data.categories.find(item=>item.category===category)||{category,baseAmountMinor:49900,additionalBranchAmountMinor:0}));
  return <form className="ait-form" onSubmit={event=>{event.preventDefault();if(window.confirm('Save these recurring prices? They apply to new subscriptions only. Existing mandates keep their agreed price.'))onSave({approved,version:'owner-'+Date.now(),period,currency:'INR',startingAmountMinor:49900,categories:rates});}}><h2>Recurring pricing</h2><p>Small shops start at ₹499/month. Set approved category and branch rates here. AI recommendations must not change an existing AutoPay mandate.</p><label>Billing period<select value={period} onChange={event=>setPeriod(event.target.value)}><option value="month">Monthly</option><option value="year">Yearly</option></select></label>{rates.map((item,index)=><div className="ait-panel ait-form" key={item.category}><h3>{item.category}</h3><div className="ait-form-grid">{[['baseAmountMinor','Base price (₹)'],['additionalBranchAmountMinor','Each extra branch (₹)']].map(([key,label])=><label key={key}>{label}<input type="number" step="0.01" min={key==='baseAmountMinor'?499:0} value={item[key]/100} onChange={event=>setRates(rates.map((rate,i)=>i===index?{...rate,[key]:Math.round(Number(event.target.value)*100)}:rate))}/></label>)}</div></div>)}<label className="ait-checkbox"><input type="checkbox" checked={Boolean(approved)} onChange={event=>setApproved(event.target.checked)}/>Approve these rates for new checkouts after payment configuration</label><button disabled={busy} className="btn-primary">Save pricing</button></form>;
}
