// Prepare unsigned iOS artifacts on the public company repository's hosted Mac.
import {execFileSync} from 'node:child_process';import {mkdir,writeFile} from 'node:fs/promises';import {resolve} from 'node:path';
const credential=execFileSync('git',['credential','fill'],{input:'protocol=https\nhost=github.com\n\n',encoding:'utf8',stdio:['pipe','pipe','pipe']});
const token=credential.split(/\r?\n/).find(s=>s.startsWith('password='))?.slice(9);
if(!token)throw new Error('GitHub authentication unavailable.');
const base='https://api.github.com/repos/infogalletrix/AllinoneToday',headers={Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};
async function api(path,method='GET',body){const r=await fetch(base+path,{method,headers,body:body?JSON.stringify(body):undefined});if(!r.ok)throw new Error('GitHub request failed: '+r.status);return r.status===204?null:r.json();}
const mode=process.argv[2]||'status';
if(mode==='dispatch'){const repo=await api('');if(repo.private)throw new Error('Private-repository Mac runner billing requires confirmation.');await api('/actions/workflows/ios.yml/dispatches','POST',{ref:'main'});console.log('Unsigned iOS builds requested on the public repository. No Apple credentials or App Store upload are involved.');}
else if(mode==='status'){const r=await api('/actions/workflows/ios.yml/runs?per_page=3');for(const x of r.workflow_runs){console.log(JSON.stringify({id:x.id,status:x.status,conclusion:x.conclusion,commit:x.head_sha,url:x.html_url}));const jobs=await api(`/actions/runs/${x.id}/jobs`);for(const j of jobs.jobs)console.log(JSON.stringify({job:j.name,status:j.status,conclusion:j.conclusion,steps:j.steps?.filter(s=>s.status==='in_progress'||s.conclusion==='failure').map(s=>({name:s.name,status:s.status,conclusion:s.conclusion}))}));}}
else if(mode==='download'){const id=process.argv[3];if(!/^\d+$/.test(id||''))throw new Error('Provide a verified workflow run ID.');const result=await api(`/actions/runs/${id}/artifacts`);const directory=resolve(import.meta.dirname,'../artifacts/ios');await mkdir(directory,{recursive:true});for(const a of result.artifacts){if(!a.name.startsWith('allinonetoday-')||a.expired)continue;const redirect=await fetch(a.archive_download_url,{headers,redirect:'manual'});const location=redirect.headers.get('location');if(!location)throw new Error('Artifact download was not available.');const r=await fetch(location);if(!r.ok)throw new Error('Artifact download failed.');const name=a.name.replace(/[^a-zA-Z0-9_-]/g,'')+'.zip';await writeFile(resolve(directory,name),Buffer.from(await r.arrayBuffer()));console.log('Downloaded unsigned artifact: '+name);}}
else throw new Error('Use dispatch, status, or download RUN_ID');
