import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {hashPassword,verifyPassword,matchesSignature,newToken,tokenHash} from '../src/security.js';import {quote} from '../src/pricing.js';import {verifyCheckout,handleWebhook} from '../src/billing.js';
test('Passwords use salted hashes and reject wrong passwords',async()=>{const a=await hashPassword('LongPassword1!'),b=await hashPassword('LongPassword1!');assert.notEqual(a,b);assert.equal(await verifyPassword('LongPassword1!',a),true);assert.equal(await verifyPassword('WrongPassword1!',a),false);});
test('Session identifiers are random and stored by hash',()=>{const a=newToken(),b=newToken();assert.notEqual(a,b);assert.notEqual(a,tokenHash(a));assert.equal(tokenHash(a).length,64);});
test('Signatures reject tampering, missing secrets and malformed input',()=>{const signature=createHmac('sha256','test-only-secret').update('payment|subscription').digest('hex');assert.equal(matchesSignature('payment|subscription',signature,'test-only-secret'),true);assert.equal(matchesSignature('wrong',signature,'test-only-secret'),false);assert.equal(matchesSignature('wrong','not-hex','test-only-secret'),false);assert.equal(matchesSignature('wrong',signature,''),false);});
const pricing={approved:true,version:'test-only',period:'month',categories:[{category:'Vehicles',baseAmountMinor:49900,additionalBranchAmountMinor:15000}]};
test('Quotes are server-calculated with branch and category validation',()=>{assert.equal(quote(pricing,'Vehicles',3).amountMinor,79900);for(const branches of [0,-1,101,1.5])assert.throws(()=>quote(pricing,'Vehicles',branches));assert.throws(()=>quote(pricing,'Not a category',1));assert.throws(()=>quote({...pricing,approved:false},'Vehicles',1));});
test('Unapproved billing cannot be quoted',()=>assert.throws(()=>quote({approved:false,categories:[]},'Vehicles',1)));
test('Unknown or cross-account checkout cannot grant access',async()=>{let writes=0;const pool={query:async sql=>{if(!sql.startsWith('SELECT'))writes++;return {rows:[]};}};await assert.rejects(verifyCheckout(pool,{id:'a'},{requestId:'b',subscriptionId:'sub_fake',paymentId:'pay_fake',signature:'0'.repeat(64)}));assert.equal(writes,0);});
test('Invalid webhook never touches storage',async()=>{const pool={connect:()=>assert.fail('invalid signature accessed database')};await assert.rejects(handleWebhook(pool,Buffer.from('{}'),'bad','test-event'));});
